language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: RUR54Yv52YZfaHjy9vi7/98VMh8+xZr3ul2/D+otJHeFEjKYVd5iVFCYEweaH6jSPD3dLEwtn3QTuz0lM3qSClIS5Cp9mTVP3U9iLrOF36iGhjf9CJ8esaGiCD2/2ccJzMSwkQ99GtJwaS613UWubnYBgeQ9tyuDqGY5Sjdsn4nZro87zXBt/UHbSnUlcYX9zEJIUlgvRl19OGpcYao2bcy92Xcd0rkGRldLto09ke4dmjS7+GgtmJdCtTqPGLdww7Qj+p2a0fUDY6Nhlea4N+OxHmTdMpbR5+lLzj19oz/6twVszT/Z53mmOYA8VU7k/5TdBk10rJHtbvBz4Cj/l9yICxNIhB54bbn5H8ogOlmVWfNnrt6J/2MFVSGiHoVGmzr6zW8OHQfhB4yWPJdyrAHiohahnTiUfIO9ZxPU7Xvs7W+8uWeI10XiyFPXEagzztoduLZE+jPYTce266rlkgDpBG9dLnEGEE8rsePg+ANIoa6Fg/e2x34WFlqzDTF6f/nrCKLWCs9tgKSyXNDwgJqMDl3EQ1rGHwGbFihZJu9RW08TaZLmolhSG6v/N4+ZU2C6p6VRL8ccU0hjFtCyQjifuCgUlwqdnVQsGQF85aksJZnBrFRx/KdvAXrKtThp4O+JzMqiqsEU4c7f848VQooJN3y2DbNvqpLJYtBpPl4=