language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: BeFXmgb4pVWXhQ8ybhfILIJWsPzQgJ0vlQseB6KSiBAKITMJ6XxALeRfZwX7amulJ2oZxJZE1jtF3QujuLYjf2bsT4kTfVI24RLIooEQxmSbzE2KpAqyfFxKwaLj3Q/ZuDC1G2XMuxt4Xb4DTThQcw5HPwZy3sY3UVizSTebi2S30/x8OHxMu+SLkcw5zqcjObZ0LPKtGalQMHK7yEmMThjxwpF3aIxuAWW0mXhENVvg24ghVV/LSEskG4s46Ko1lwTl8xEcSizhfE3cETg9Yz2wHU2v4kJqJCssZpqv1/jkL3QrzU9szDs+mJqRCtvF8UwYp9YfJx4jvU4BkoHHPVQqPEEw5GQtUalYe16OKXiRy7wdi9Nwe+LRtv4/RbovQAWHr0LIptqxCo8/VJ+zsjDmysfKGcOe0RKnjW84cJwDlUABG/ZUGv5zLi1DqMlOgkFtxVnZjy3i+HVkzxRfOcnj4C5cjUqLexY8qVxwXj3ti1teIEDM/nC32UYewHiyMcJK7JPmPkob4oNB/4ZfbKy0s8SL6moQq9k6OfxkSzBDJQlPXdsyymSlqtZQuIxHQfQflZeZblKu70jYl2Nx6nT7QvNl9hj3OrjianNyd3kaEvSWXLMz7IkcKdPGEzcVeq72dW2Unfwqwe0EBdVGr7QqzP2kCsdYtmvx225xKGk=