language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: W53fpdEaVtvaQj8TYF+iSMyk7twyRrZmUdRt2VHN4xhvEO+1aVDiBJVoZMCk8J7kiSErKzgDc8zmuJ1n6OMj7/OiJF96yMcvG9KlvfmYWhAqQc8ajEHy3HEdVlQyADF93Pm4lGR4Ayj2ysLe1RCWS+iyMTzExTxmeaM+an7rf2zv+8wBhdLhQ66gIoERJw2KK7BTyOZACgM/tFn05liaq7G/OC3T7y7TOVS+/d5C0w2u62w1/n+TYc97M/oszNLCQy1BQZI0bc0nPeVwht1ZHcAxaqExeT1kGvxZn1dqkRRKIC3yNPLmbboOnwUNacvn8WqNlFiw5CNMpUE5QYZDg84EAikGUhcq2w1IfXDgTTn9ojFfQga9d+ge3w1JielfZAE2v/VlEH/jiPBJc0bpth4IGWll4KktLrvBqgkEREUVFT0mZbapuRkU7RXQ53q0vuDmp+4w+t1gPXL6Jih9AZqQWQCcZC2tXflK+2nw9HqkGuEm9VwdXH5TeUoNu8X+GSO8jtgd27lyuJ/03NE17/gFhUs0CJ3UG1DIL96n5wX+b2aGqjutURIbd62brVTp6JFJLM9IKk3vemdWgiQwgD0+FKP362gKijJz/C3nSzMgjaqkoTBe93yKWgY+KsLeXCw+mBTGbcFMNyZncWmClLokz7qzKM09r+TBL+SIZSU=